### ISSUE TITLE
Modify qilgandan keyin backni bossa shu function cancel bo`lishi kerak hozir esa screendan tashqariga chiqib ketayapti

### ISSUE THREAD

**Issue by Javohir8809** [SamarkandTour/Samapp-mobile#26]
![013](https://cloud.githubusercontent.com/assets/18481216/14566038/43ad7a76-0347-11e6-9378-b6a03d1564fb.jpg)

**Comment by SamarkandTour** [comment]
Agar shu oynada yana item qo'shgandan keyin Back button bossa yana birxil muammo chiqadi.

**Comment by alexb007** [comment]
Menda bunaqa muammo yo'qku kimni telida bo'lyapti
