### ISSUE TITLE
Itinerary o'zgartish mode da rasmni bossa rasm o'chrib qoladi.

### ISSUE THREAD

**Issue by comseong** [SamarkandTour/Samapp-mobile#3]
Itinerary o'zgartish mode da rasmni bossa rasm o'chrib qoladi.
![Uploading 1.png…]()

**Comment by alexb007** [comment]
Itinerary o'zgartish mode da rasmni bossa rasm o'chrib qoladi.
(FIXED)

**Comment by comseong** [comment]
Fix uchun code push qilgandan keyin shu issue ni yopiq qilaman.

**Comment by comseong** [comment]
Resolved at new version
