### ISSUE TITLE
Uzunlikda 5164.5km chiqayapt.

### ISSUE THREAD

**Issue by SamarkandTour** [SamarkandTour/Samapp-mobile#37]
![image](https://cloud.githubusercontent.com/assets/13328310/14611654/d247d472-05ac-11e6-9d1e-e8c6c047cf17.png)

**Comment by alexb007** [comment]
menimcha dolmachinoning locationi xato berilgan

**Comment by Javlon1410** [comment]
menimcha ham shunday buni hozir to'g'irlayman

**Comment by alexb007** [comment]
ismlardaham sonlarni olib tashlash kerak
