### ISSUE TITLE
uzbek va ingliz tilida appi ishlamayapti

### ISSUE THREAD

**Issue by Javlon1410** [SamarkandTour/Samapp-mobile#7]
![photo_2016-04-14_21-26-09](https://cloud.githubusercontent.com/assets/18467743/14536962/6dcab4fe-028e-11e6-9df6-a434607ab1f3.jpg)
uzbek tili yoki ingliz tilini tanlansa programm stoped deb chiqib ketyapti

**Comment by comseong** [comment]
Temporary issue of local compiled version.
